sqlite:
  adapter: sqlite3
  database: tmp/data.sqlite3
  pool: 5
  timeout: 5000

mysql:
  adapter: mysql2
  host: 127.0.0.1
  database: ranked_model_test
  pool: 5
  timeout: 5000
  username: root
  password:

postgresql:
  adapter: postgresql
  host: 127.0.0.1
  database: ranked_model_test
  pool: 5
  timeout: 5000
  username: postgres
  password:
  min_messages: ERROR
