sqlite:
  adapter: sqlite3
  database: tmp/data.sqlite3
  pool: 5
  timeout: 5000

mysql:
  adapter: mysql2
  database: ranked_model_test
  pool: 5
  timeout: 5000
  username: root

postgresql:
  adapter: postgresql
  database: ranked_model_test
  pool: 5
  timeout: 5000
  username: postgres
  min_messages: ERROR
